<?php

namespace Obokaman\Playground\Infrastructure\Repository\Doctrine\Skill;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
