<?php

namespace Obokaman\Playground\Infrastructure\Repository\Doctrine\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
